server {
    listen 443 ssl;
    server_name admin.linantravel.cn;
    ssl_certificate /etc/letsencrypt/live/linan-test/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/linan-test/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    auth_basic "Linan test environment";
    auth_basic_user_file /etc/nginx/linan-test.htpasswd;
    root /opt/linan-test/app/apps/admin/dist;
    index index.html;

    location /api/ {
        proxy_pass http://127.0.0.1:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 443 ssl;
    server_name api.linantravel.cn;
    ssl_certificate /etc/letsencrypt/live/linan-test/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/linan-test/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    auth_basic "Linan test environment";
    auth_basic_user_file /etc/nginx/linan-test.htpasswd;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
