server {
    listen 80;
    server_name admin.linantravel.cn api.linantravel.cn;

    location /.well-known/acme-challenge/ {
        root /var/www/linan-acme;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
